### PR TITLE
Separate folder and files in folder section

### PR DESCRIPTION
**Pull request by TSI-ashishsharma**
Separate files and folders in the left side menu Folder, also change the max version in info.xml to 27.

### CODE REVIEW

**Comment by tsdicloud** [comment]
**App customisations stick to the same rules as any other upstream fork customisations, same as server.**
Under this aspect, sorry, this PR is completely nonsense.

If you work on an app customisations, you need to clean up the fork first as `master` branch MUST become a pure mirror for upstream as for server.

I don't understand this pull request at all, as it is neither mergeable nor a decomposed customisation.

**Comment by TSI-ashishsharma** [comment]
Hi @tsdicloud. This PR is related to Version25.0.5.
Because after this version when we enable it from apps section it gives composer error till version 27 and didn't mention how to solve those composer related errors on description. Also checked on dev2 version for photos app. it is same v25.0.5
So first we create a separate master branch from tag 25.0.5 and perform our changes in another branch and then raise a PR

**Comment by tsdicloud** [comment]
Can you please stop justifying and start working in a structured way?
Have you ever read the new delivery model concept? (you obviously couldn't, or at least you have no understanding of it).
Just imitating behavior from other projects will have the result like here.

To support the new deliever y model, you have to:
(1) Extract all changes that have beem made to master into auto-merging branches
(2) Roll back master into a pure upstream mirror
      (be warned: I will hard reset all commits from our side before finally syncing upstream and adding the new build mechanism, so all customisations on master will be gone forever!)
(3) Incrementally add each patch independently
(4) Implement unittest for each expected view or behavioral change, most tests in Javascript
       (which would be much easier with Jest...)
(5) Then, finally, you can raise a custom PR to include a branch into new build.

All other ways may lead to a wildly-mixed ("ramshackled") temporary app that "somehow" works, but
not the reason why we are doing this exercise and giving you time for refactoring.

**Comment by TSI-ashishsharma** [comment]
Hi @tsdicloud 
I am not able to follow ur step #1 and not able to reset the master branch
image

 Because don't have access.

**Comment by tsdicloud** [comment]
Why are you starting with step 2?
Your focus is on step 1, and you will NOT do step 2 as you tried silently on your own.

So: new rights work as expected. Focus on clean code redesign, test it on your developer machine,
deliver 90% fully working code with small changes for new delivery model.

**Comment by TSI-ashishsharma** [comment]
Hi @tsdicloud 
I finished step 1 and didn't find any commits from our side. Remove all commits from our side from the master branch and now waiting for the second step where I am facing the access issue.

**Comment by tsdicloud** [comment]
Are you honest with the comment?

- Step 1 is ready if you have fully redesigned your code according to new deivery model
- Proven with (Javascript) unittests that it is 100% working.

Merging means that you are completely done and will not do any further work on it afterwards.
So obviously, even linting breaks.
You still hardcode style, you massively change Nextcloud standard, ...

You have much too many changes to even think of going into continuous integration
So, can't believe that you have the slightest right to wait with all the work ahead ...
Don't believe that I cannot see that you spend ridiculous few time on that one, which
is a big problem.

We can talk about that in weeks again if you finally deliver product and maintenance quality.

**Pull request closed without merging**
