### PR TITLE
[Master] Change application name from Photos to Media

### PR DESCRIPTION
**Pull request by TSI-ashishsharma**
Change application name from Photos to Media

### CODE REVIEW

**Comment by tsdicloud** [comment]
We never rename a customized app by completely change the name, and also not by a name different from the repo name.
For me, this change does not make any sense from the behavior perspective, it is nowhere visible for the end user.

But it cause risk and trouble for deployment.

**Comment by TSI-ashishsharma** [comment]
@tsdicloud As per the initial requirement, we changed the app name which is there from initial development. if any change is required please create a ticket with details, so we can update it accordingly.

**Comment by tsdicloud** [comment]
This not even has a ticket reference number, so there is no documentation of the requirement. It could only mean that photos app should not be shown as Media on the UI, which is a theming case and not a core code change.

Candidate fro removal.

**Comment by tsdicloud** [comment]
Not needed anymore, Translation solution in nmctheme

**Pull request closed without merging**
