### PR TITLE
[Master] Separate files and folders for the left side menu Folders.

### PR DESCRIPTION
**Pull request by TSI-ashishsharma**
Separate files and folder view design for "Folders" left side menu.

### CODE REVIEW

**Comment by tsdicloud** [comment]
Please analyse this thoroughly.
I think that the changed code from Nextcloud does a similar fix as the longer variation (that even does not lint)

Is this fix actually needed, and if so: why is tis bugfix not accepted by Nextcloud?

**Comment by tsdicloud** [comment]
This is an incremental change for another change on photo app and will never reliable work with new delivery model as it is not an independent customisation.

**Comment by TSI-ashishsharma** [comment]
As per the requirement, we changed it initially.

**Comment by tsdicloud** [comment]
Please check. We aligned to put the component/functional changes to app.
To keep it available for pushing upstream, it should be styled with Nextcloud standard look&feel.
If we need to change visual appearance of a photos component for NMC; then we do the styling in themes.

Sorry for the confusion.

**Pull request closed without merging**
