### PR TITLE
[Master] Theme related changes

### PR DESCRIPTION
**Pull request by TSI-ashishsharma**
Theme related changes and language translation.

### CODE REVIEW

**Comment by tsdicloud** [comment]
Can be completely done in theming, so why here and change another app?

**Comment by TSI-ashishsharma** [comment]
@tsdicloud , As you suggested we moved this change from themes to app-level that's the reason we create this PR and code removed from themes.

**Comment by TSI-ashishsharma** [comment]
> @tsdicloud , As you suggested we moved this change from themes to app-level that's the reason we create this PR and code removed from themes.

Any update on this?

**Comment by tsdicloud** [comment]
Meanwhile, everything done in nmctheme

**Pull request closed without merging**
